import type { MRT_Cell, MRT_TableInstance } from "material-react-table";
import { useCreateSourceWithAutogeneratedName } from "~/features/source/facets/createSourceWithNewName";
import type { SourceTableItem } from "~/features/source/Source";

export const useHandleCreateSource = (
  table: MRT_TableInstance<SourceTableItem>
) => {
  const createSource = useCreateSourceWithAutogeneratedName();
  return () =>
    createSource.mutate(undefined, {
      onSuccess: (created) => {
        setTimeout(() => {
          const row = table.getRow(created.id.toString());
          const cell = row
            .getAllCells()
            .find((cell) => cell.column.id === "name");
          if (!cell) {
            console.error("Can't find a cell to edit");
            return;
          }
          table.setEditingCell(
            cell as unknown as MRT_Cell<SourceTableItem, unknown>
          );
        }, 500);
      },
    });
};
