import { getFirstUnusedName } from "~/utils/getFirstUnusedName";
import { useCreateSource } from "../api/sourcesApi";
import { useSources } from "./allSources";

export const useCreateSourceWithAutogeneratedName = () => {
  const { data: sources = [] } = useSources();
  return useCreateSource(() =>
    getFirstUnusedName(
      sources.map((s) => s.name),
      "Источник"
    )
  );
};
